destination: ./_site
lsi: false
port: 4000
highligher: true
markdown: kramdown
permalink: date
title: Scientech
copy: Scientific Technology Bureau, LLC 2003 — 2016
email: incoming@scientech.com.ua
github_username: scientech-com-ua
plusgoogle_username: scientech_com_ua
